twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
     timetable: '@App\Twig\TimeTableExtension'
     comment: '@App\Twig\CommentExtension'

when@test:
    twig:
        strict_variables: true